#!/usr/bin/perl -w

# Generate user-space syscall stubs.

print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
  my $name = shift;
  print ".global $name\n";
  print "$name:\n";
  print "  li a7, SYS_$name\n";
  print "  ecall\n";
  print "  ret\n";
}

entry("print");
entry("fork");
entry("exit");
entry("wait");
entry("exec");
entry("getpid");
